# Generated by Django 6.0.3 on 2026-05-07 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignments/%Y/%m/%d/', verbose_name='Файл')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Оригинальное имя')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('assigned_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='managers.assignedtask', verbose_name='Назначенная задача')),
                ('project_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='managers.projectassignment', verbose_name='Назначение проекта')),
            ],
            options={
                'verbose_name': 'Прикреплённый файл',
                'verbose_name_plural': 'Прикреплённые файлы',
            },
        ),
    ]
