# Generated by Django 6.0.3 on 2026-05-07 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Подзадача',
                'verbose_name_plural': 'Подзадачи',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершена')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена в')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок')),
                ('total_time', models.FloatField(default=0.0, verbose_name='Всего времени (сек)')),
                ('is_timer_running', models.BooleanField(default=False, verbose_name='Таймер запущен')),
                ('last_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Последний старт')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Комментарий к задаче',
                'verbose_name_plural': 'Комментарии к задачам',
            },
        ),
        migrations.CreateModel(
            name='DailyWorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('total_time', models.FloatField(default=0.0, verbose_name='Всего секунд')),
                ('is_timer_running', models.BooleanField(default=False, verbose_name='Таймер запущен')),
                ('last_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Последний старт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Дневная сессия',
                'verbose_name_plural': 'Дневные сессии',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('hourly_rate', models.FloatField(default=0.0, verbose_name='Часовая ставка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='SubTaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='developers.subtask')),
            ],
            options={
                'verbose_name': 'Комментарий к подзадаче',
                'verbose_name_plural': 'Комментарии к подзадачам',
            },
        ),
    ]
